site_name: Integral por cuadratura gaussiana

theme:
  name: "material"

plugins:
  - mkdocstrings
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
- javascripts/mathjax.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Problema: index.md 
  - Explicación: explanation.md
  - Ejemplo de uso: tutorial.md
  - Documentación: reference.md

